// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twmagwjzmuqxwgnauybl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3bWFnd2p6bXVxeHdnbmF1eWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NjcxODksImV4cCI6MjA1MDA0MzE4OX0.Nh7mGhIpioNKxmb7crN_S1pLghQlfScXKkPkJUoHg3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);